service:
  namespace: "nuboxido"
  image:
    repository: "localhost:5000/skaffold"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  env:
    RUST_LOG: "info"

triggers:
- broker: "default"
  namespace: "all-eventing"
  uri: "/"
  filterAttributes:
  type: com.acme.events.something
  source: com.acme.apps.ingress
