apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $label, $value := .Values.service.env }}
  {{ $label }}: {{ $value }}
  {{- end }}