apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
spec:
  template:
    metadata:
      labels: *labels
      annotations:
        {{ toYaml .Values.service.annotations | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{.Values.image.registry}}/{{.Values.image.repository}}:{{.Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8080
        resources:
          {{ toYaml .Values.service.resources | nindent 10 }}
        env:
        - name: HELM_RELEASE_NAME
          value: {{ .Release.Name | quote }}
        - name: HELM_RELEASE_REVISION
          value: {{ .Release.Revision | quote }}
        - name: HELM_CHART_NAME
          value: {{ .Chart.Name | quote }}
        - name: HELM_CHART_VERSION
          value: {{ .Chart.Version | quote }}
        - name: HELM_RELEASE_NAMESPACE
          value: {{ .Release.Namespace | quote }}
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-env-config"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: false
        # Not yet supported in Knative? See: https://github.com/knative/serving/issues/10037
        # startupProbe:
        #   failureThreshold: 10
        #   periodSeconds: 1
        #   timeoutSeconds: 1
        #   httpGet:
        #     path: /health/started
        readinessProbe:
          failureThreshold: 1
          periodSeconds: 5
          timeoutSeconds: 1
          httpGet:
            path: /health/ready
        livenessProbe:
          failureThreshold: 5
          periodSeconds: 5
          timeoutSeconds: 1
          httpGet:
            path: /health/live
